# **과제 : Chapter 2 연습문제**




##  연습문제 1번

In [ ]:
import numpy as np
my_vector = np.array([1,2,3,4,5,6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

## 연습문제 2번

In [ ]:
import numpy as np
first_matrix = np.array([[1,2,3],[4,5,6]])
second_matrix = np.array([1,2,3])
first_matrix + second_matrix

array([[2, 4, 6],
       [5, 7, 9]])

## 연습문제 3번

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 연습문제 4번

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## 연습문제 5번

In [ ]:
arr1 = np.arange(0,10)
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 연습문제 6번

In [ ]:
arr2 = np.arange(0,9)
arr2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 연습문제 7번

In [ ]:
arr3 = np.random.random(9)
arr3.reshape(3,3)

array([[0.51131271, 0.14850457, 0.96301713],
       [0.75236798, 0.83109953, 0.4883598 ],
       [0.94877292, 0.38691581, 0.04988768]])

## 연습문제 8번

In [ ]:
arr4 = np.random.random((10,10))
"최소값 : {}, 최대값 : {}".format(arr4.min(), arr4.max())

'최소값 : 0.001607424037997851, 최대값 : 0.9999914057483477'

## 연습문제 9번

In [ ]:
A = np.ones(9).reshape(3,3)
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


## 연습문제 10번

In [ ]:
A = np.zeros((5,5))
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


## 연습문제 11번

In [ ]:
arr5 = np.random.random((3,3))
print(arr5)

[[0.30835506 0.742537   0.1039941 ]
 [0.61831479 0.06164538 0.69754717]
 [0.41176496 0.62520435 0.25968625]]


In [ ]:
arr6 = (arr5-np.mean(arr5))/(np.std(arr5))
print(arr6)

[[-0.48309939  1.30820955 -1.32623351]
 [ 0.79570471 -1.50095207  1.12259456]
 [-0.05646009  0.82412904 -0.68389281]]
