# 연습문제 3번


In [ ]:
import numpy as np

epsilon = 0.0000001

def step_func(t) :
  if t > epsilon : return 1
  else : return 0
  

In [ ]:
step_func(0)

0

In [ ]:

def perceptron_fit(X, Y, epochs = 10):
  global W
  eta = 1.0

  for t in range(epochs):
    print("epoch =" , t, "=================================" )
    for i in range(len(X)):
      predict = step_func(np.dot(X[i], W))
      # print("predict:", predict)
      error = Y[i] - predict
      # print("Error:", error)
      print(eta, error, X[i])
      W += eta * error * X[i]
      print("현재 처리 입력 = ", X[i], "정답 = ", Y[i], "출력 =", predict, "변경된 가중치 = ", W)
      print("=========================================")

In [ ]:
def perceptron_predict(X,Y):
  global w
  for x in X :
    print(x[0], x[1], "->", step_func(np.dot(x,W)))

##### (a)

In [ ]:
X = np.array([
              [-1,1,1],
              [-1,0,1],
              [-1,-1,1],
              [0,1,1],
              [1,1,1],
              [1,0,1],
              [0,-1,1],
              [1,-1,1]
])
y = np.array([1,1,1,1,0,0,0,0])
W = np.zeros(len(X[0]))

perceptron_fit(X,y,2)
perceptron_predict(X,y)

epoch = 0 =================================
현재 처리 입력 =  [-1  1  1] 정답 =  1 출력 = 0 변경된 가중치 =  [-0.2  0.2  0.2]
현재 처리 입력 =  [-1  0  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2  0.2  0.2]
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2  0.2  0.2]
현재 처리 입력 =  [0 1 1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2  0.2  0.2]
현재 처리 입력 =  [1 1 1] 정답 =  0 출력 = 1 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [ 0 -1  1] 정답 =  0 출력 = 0 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [ 1 -1  1] 정답 =  0 출력 = 0 변경된 가중치 =  [-0.4  0.   0. ]
epoch = 1 =================================
현재 처리 입력 =  [-1  1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [-1  0  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.4  0.   0. ]
현재 처리 입력 =  [0 1 1] 정답 =  1 출력 = 0 변경된 가중치 =  [-0.4  0.2  0.2]
현재 처리 입력 =  [1 1 1] 정답 =  0 출력 = 0 변경된 가중치 =  [-0.4  0.2  0.2]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [-0.4  0.2  0.2]
현재 처리 

##### (b)

In [ ]:
X = np.array([
              [-1,-1,1],
              [0,-1,1],
              [1,-1,1],
              [-1,0,1],
              [1,0,1],
              [-1,1,1],
              [0,1,1],
              [1,1,1]
])
y = np.array([1,1,1,0,0,0,0,0])
W = np.zeros(len(X[0]))

perceptron_fit(X,y,2)
perceptron_predict(X,y)

epoch = 0 =================================
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 0 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [ 0 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [ 1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [-1  0  1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [-1  1  1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [0 1 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [1 1 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
epoch = 1 =================================
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [ 0 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [ 1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [-1  0  1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]
현재 처리 입력 =  [-1  1  1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0. ]


##### (c)

In [ ]:
X = np.array([
              [-1,-1,1],
              [0,-1,1],
              [1,-1,1],
              [-1,0,1],
              [1,0,1],
              [-1,1,1],
              [0,1,1],
              [1,1,1]
])
y = np.array([1,1,1,1,1,0,1,1])
W = np.zeros(len(X[0]))

perceptron_fit(X,y,2)
perceptron_predict(X,y)

epoch = 0 =================================
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 0 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [ 0 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [ 1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [-1  0  1] 정답 =  1 출력 = 1 변경된 가중치 =  [-0.2 -0.2  0.2]
현재 처리 입력 =  [1 0 1] 정답 =  1 출력 = 0 변경된 가중치 =  [ 0.  -0.2  0.4]
현재 처리 입력 =  [-1  1  1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0.2 -0.4  0.2]
현재 처리 입력 =  [0 1 1] 정답 =  1 출력 = 0 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [1 1 1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
epoch = 1 =================================
현재 처리 입력 =  [-1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [ 0 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [ 1 -1  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [-1  0  1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [1 0 1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 0.2 -0.2  0.4]
현재 처리 입력 =  [-1  1  1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.2 -0.2  0.4]


# 연습문제 5번 코드 확인

In [ ]:
epsilon = 0.0000001

X = np.array([
              [0,1,-1],
              [1,0,-1],
              [1,2,-1],
              [2,1,-1]
])
y = np.array([0,0,1,1])
W = np.zeros(len(X[0]))
W[-1]=-1.0
print(W)

perceptron_fit(X,y,3)
perceptron_predict(X,y)

[ 0.  0. -1.]
epoch = 0 =================================
1.0 -1 [ 0  1 -1]
현재 처리 입력 =  [ 0  1 -1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0. -1.  0.]
1.0 0 [ 1  0 -1]
현재 처리 입력 =  [ 1  0 -1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0. -1.  0.]
1.0 1 [ 1  2 -1]
현재 처리 입력 =  [ 1  2 -1] 정답 =  1 출력 = 0 변경된 가중치 =  [ 1.  1. -1.]
1.0 0 [ 2  1 -1]
현재 처리 입력 =  [ 2  1 -1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 1.  1. -1.]
epoch = 1 =================================
1.0 -1 [ 0  1 -1]
현재 처리 입력 =  [ 0  1 -1] 정답 =  0 출력 = 1 변경된 가중치 =  [1. 0. 0.]
1.0 -1 [ 1  0 -1]
현재 처리 입력 =  [ 1  0 -1] 정답 =  0 출력 = 1 변경된 가중치 =  [0. 0. 1.]
1.0 1 [ 1  2 -1]
현재 처리 입력 =  [ 1  2 -1] 정답 =  1 출력 = 0 변경된 가중치 =  [1. 2. 0.]
1.0 0 [ 2  1 -1]
현재 처리 입력 =  [ 2  1 -1] 정답 =  1 출력 = 1 변경된 가중치 =  [1. 2. 0.]
epoch = 2 =================================
1.0 -1 [ 0  1 -1]
현재 처리 입력 =  [ 0  1 -1] 정답 =  0 출력 = 1 변경된 가중치 =  [1. 1. 1.]
1.0 0 [ 1  0 -1]
현재 처리 입력 =  [ 1  0 -1] 정답 =  0 출력 = 0 변경된 가중치 =  [1. 1. 1.]
1.0 0 [ 1  2 -1]
현재 처리 입력 =  [ 1  2 -1] 정답 =  1 출력 = 1 변경된 가중치 =  [1

# 연습문제 8번 코드 확인

In [ ]:
from sklearn.linear_model import Perceptron

X = np.array([
              [0.1,0.7,1],
              [0.3,0.6,1],
              [0.45,0.15,1],
              [0.6,0.3,1],
              [0.1,1,1],
              [0.3,1,1],
              [0.7,0.7,1],
              [0.9,0.45,1]
])
y = np.array([1,1,1,1,-1,-1,-1,-1])

clf = Perceptron(tol = 1e-3, random_state = 0)

clf.fit(X, y)

print(clf.predict(X))

[ 1  1  1  1 -1 -1 -1 -1]


In [ ]:
import numpy as np
X=np.array([
    [0,1,1],
    [1,0,1],
    [1,2,1],
    [2,1,1]
])
W=np.zeros(len(X[0]))
W[-1]=-1.0
print(W)

[ 0.  0. -1.]


In [ ]:
import numpy as np

epsilon=0.0000001

def step_func(t):
    if t >epsilon: return 1
    else: return 0

X=np.array([
    [0,1,1],
    [1,0,1],
    [1,2,1],
    [2,1,1]
])

y=np.array([0,0,1,1])
W=np.zeros(len(X[0]))
W[-1]=-1.0


def perceptron_fit(X,Y,epochs=10):
    global W
    eta=1.0
    for t in range(epochs):
        print("epoch=",t,"=========")
        for i in range(len(X)):
            predict=step_func(np.dot(X[i],W))
            error=Y[i]-predict
            W+=eta*error*X[i]
            print("현재 처리 입력=",X[i],"정답=",Y[i],"출력=",predict,"변경된 가중치=",W)
        print("========================")

def perceptron_predict(X,Y):
    global W
    for x in X:
        print(x[0],x[1],"->",step_func(np.dot(x,W)))

perceptron_fit(X, y,6)
perceptron_predict(X,y)

epoch= 0 =========
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [ 0.  0. -1.]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [ 0.  0. -1.]
현재 처리 입력= [1 2 1] 정답= 1 출력= 0 변경된 가중치= [1. 2. 0.]
현재 처리 입력= [2 1 1] 정답= 1 출력= 1 변경된 가중치= [1. 2. 0.]
epoch= 1 =========
현재 처리 입력= [0 1 1] 정답= 0 출력= 1 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 2 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [2 1 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
epoch= 2 =========
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 2 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [2 1 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
epoch= 3 =========
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 0 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [1 2 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= [2 1 1] 정답= 1 출력= 1 변경된 가중치= [ 1.  1. -1.]
epoch= 4 =========
현재 처리 입력= [0 1 1] 정답= 0 출력= 0 변경된 가중치= [ 1.  1. -1.]
현재 처리 입력= 