# 퍼셉트론 구현 1

In [1]:
epsilon = 0.0000001

def perceptron(x1, x2):
  w1, w2, b = 1.0, 1.0, -1.5
  sum = x1*w1 + x2*w2 + b
  if sum > epsilon :
    return 1
  else :
    return 0

print(perceptron(0,0))
print(perceptron(1,0))
print(perceptron(0,1))
print(perceptron(1,1))

0
0
0
1


# 퍼셉트론 구현 2 : 배열 사용

In [2]:
import numpy as np
epsilon = 0.0000001

def perceptron(x1, x2):
  X = np.array([x1,x2])
  W = np.array([1.0,1.0])
  B = -1.5
  sum = np.dot(W,X) + B
  if sum > epsilon :
    return 1
  else :
    return 0

print(perceptron(0,0))
print(perceptron(1,0))
print(perceptron(0,1))
print(perceptron(1,1))

0
0
0
1


# 퍼셉트론 학습 알고리즘 

In [3]:
import numpy as np

epsilon = 0.0000001

def step_func(t) :
  if t > epsilon : return 1
  else : return 0

X = np.array([
              [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]
])
y = np.array([0,0,0,1])
W = np.zeros(len(X[0]))

In [4]:
def perceptron_fit(X, Y, epochs = 10):
  global W
  eta = 0.2

  for t in range(epochs):
    print("epoch =" , t, "=================================" )
    for i in range(len(X)):
      predict = step_func(np.dot(X[i], W))
      error = Y[i] - predict
      W += eta * error * X[i]
      print("현재 처리 입력 = ", X[i], "정답 = ", Y[i], "출력 =", predict, "변경된 가중치 = ", W)
      print("=========================================")

In [5]:
def perceptron_predict(X,Y):
  global w
  for x in X :
    print(x[0], x[1], "->", step_func(np.dot(x,W)))

perceptron_fit(X,y,6)
perceptron_predict(X,y)

epoch = 0 =================================
현재 처리 입력 =  [0 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [0 1 1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [1 1 1] 정답 =  1 출력 = 0 변경된 가중치 =  [0.2 0.2 0.2]
epoch = 1 =================================
현재 처리 입력 =  [0 0 1] 정답 =  0 출력 = 1 변경된 가중치 =  [0.2 0.2 0. ]
현재 처리 입력 =  [0 1 1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0.2  0.  -0.2]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.2  0.  -0.2]
현재 처리 입력 =  [1 1 1] 정답 =  1 출력 = 0 변경된 가중치 =  [0.4 0.2 0. ]
epoch = 2 =================================
현재 처리 입력 =  [0 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [0.4 0.2 0. ]
현재 처리 입력 =  [0 1 1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0.4  0.  -0.2]
현재 처리 입력 =  [1 0 1] 정답 =  0 출력 = 1 변경된 가중치 =  [ 0.2  0.  -0.4]
현재 처리 입력 =  [1 1 1] 정답 =  1 출력 = 0 변경된 가중치 =  [ 0.4  0.2 -0.2]
epoch = 3 =================================
현재 처리 입력 =  [0 0 1] 정답 =  0 출력 = 0 변경된 가중치 =  [ 0.4  0.2 -0.2]
현재 처리 입력 =  [0 1 1] 정답 =  0 출력 = 0 

# sklearn 으로 퍼셉트론 실습

In [8]:
from sklearn.linear_model import Perceptron

X = [[0,0],[0,1],[1,0],[1,1]]
y = [0,0,0,1]

clf = Perceptron(tol = 1e-3, random_state = 0)

clf.fit(X, y)

print(clf.predict(X))

[0 0 0 1]


# 퍼셉트론 한계 : XOR 연산 못함

In [11]:
from sklearn.linear_model import Perceptron

X = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,0]

clf = Perceptron(tol = 1e-3, random_state = 42)

clf.fit(X, y)

print(clf.predict(X))

[0 0 0 0]


# mini project : 퍼셉트론 분류

In [38]:
from sklearn.linear_model import Perceptron
epsilon = 0.0000001
X = np.array([[160,55,1],[163,43,1],[165,48,1],[170,80,1],[175, 76,1],[180,70,1]])
y = [0,0,0,1,1,1]
W = np.zeros(len(X[0]))

clf = Perceptron(tol = 1e-3, random_state = 42)

clf.fit(X, y)

print(clf.predict(X))

[0 0 0 1 1 1]


In [39]:
clf.predict([[163, 53,0]])

array([0])

In [40]:
perceptron_fit(X,y,20)
perceptron_predict(X,y)

epoch = 0 =================================
현재 처리 입력 =  [160  55   1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [163  43   1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [165  48   1] 정답 =  0 출력 = 0 변경된 가중치 =  [0. 0. 0.]
현재 처리 입력 =  [170  80   1] 정답 =  1 출력 = 0 변경된 가중치 =  [34.  16.   0.2]
현재 처리 입력 =  [175  76   1] 정답 =  1 출력 = 1 변경된 가중치 =  [34.  16.   0.2]
현재 처리 입력 =  [180  70   1] 정답 =  1 출력 = 1 변경된 가중치 =  [34.  16.   0.2]
epoch = 1 =================================
현재 처리 입력 =  [160  55   1] 정답 =  0 출력 = 1 변경된 가중치 =  [2. 5. 0.]
현재 처리 입력 =  [163  43   1] 정답 =  0 출력 = 1 변경된 가중치 =  [-30.6  -3.6  -0.2]
현재 처리 입력 =  [165  48   1] 정답 =  0 출력 = 0 변경된 가중치 =  [-30.6  -3.6  -0.2]
현재 처리 입력 =  [170  80   1] 정답 =  1 출력 = 0 변경된 가중치 =  [ 3.4 12.4  0. ]
현재 처리 입력 =  [175  76   1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 3.4 12.4  0. ]
현재 처리 입력 =  [180  70   1] 정답 =  1 출력 = 1 변경된 가중치 =  [ 3.4 12.4  0. ]
epoch = 2 =================================
현재 처리 입력 =  [160  55   1] 정답 =  0 출력 = 1 변경된 가중치 =  [-28.6

# 퍼셉트론 연습문제 9번

In [22]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
import sys

iris = load_iris()
X = iris.data[:, (0,1)]
y = (iris.target == 0).astype(np.int)

percep = Perceptron(random_state=32)
percep.fit(X,y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


Perceptron(random_state=32)

In [23]:
percep.score(X,y)

0.8533333333333334